### ISSUE TITLE
Music doesn't work

### ISSUE THREAD

**Issue by detuur** [iwalton3/plex-mpv-shim#10]
Attempting to cast music from the web player to the shim gets ignored by the shim, even though MPV is a quite capable music player in its own right. Changing the currently playing media from video to music is ignored by the shim and doesn't interrupt the video.

Inspecting the logs reveals that something does happen and the signals arrive, but there's no response.

plex-mpv-shim_1.7.13 on Windows 10 Build 18363.720
Plex 1.18.7.2457 on Linux

**Comment by iwalton3** [comment]
The application doesn’t currently support music. I think it sort of works (this could have changed), but I don’t declare the application as supporting music playback in the profile.

I could improve support for it in some ways, but adding some features like gapless playback for instance would require major rewrites of the player queueing logic. (Right now it is event-driven and doesn’t use MPV’s internal playlist.)

Of course, pull requests are welcome. You can also consider the [mopidy plugin](https://github.com/jellyfin/mopidy-jellyfin), [jellycli](https://github.com/tryffel/jellycli), and [jfmp](https://github.com/n-peugnet/jfmp) as alternatives.

**Comment by iwalton3** [comment]
Oops I wrote the wrong reply because I thought this was an issue for the Jellyfin based player. There is currently no support for music in this application, and adding it would probably be painful due to the undocumented api. I would suggest using Plexamp if that still works or Girens.

**Comment by iwalton3** [comment]
This has been released in 1.10.0 thanks to the PR #29.
