### ISSUE TITLE
Recent arch system update broke plex-mpv-shim

### ISSUE THREAD

**Issue by mauricioquintela** [iwalton3/plex-mpv-shim#112]
Issue appears to be with python's sockets, as evident by the traceback attached. Version of python-requests is 2.31.0-1 (latest)
[dump_plex.txt](https://github.com/iwalton3/plex-mpv-shim/files/15046302/dump_plex.txt)

**Comment by mauricioquintela** [comment]
Apologies, dump did not have the error codes. This one should
[dump.txt](https://github.com/iwalton3/plex-mpv-shim/files/15047679/dump.txt)

**Comment by mauricioquintela** [comment]
Apologies, dump did not have the error codes. This one is the correct one [dump.txt](https://github.com/iwalton3/plex-mpv-shim/files/15047679/dump.txt). 

Last used it on the 15th of april, it was working fine then. 

Looking through the pacman update logs,  only python updates were python-pycups (2.0.1-6 -> 2.0.4-1), python-exceptiongroup (1.2.0-1 -> 1.2.1-1), python-traitlets (5.14.2-1 -> 5.14.3-1), with none of them being dependencies. 

Looking at systemwide updates and pruning the list for unrelated programs (like discord, texlive-*, etc), I don't find much that could cause issues, apart from mpv itself [upgrades.txt](https://github.com/iwalton3/plex-mpv-shim/files/15047807/upgrades.txt).

**Comment by bassberry** [comment]
jaseg/python-mpv#273

Apparently there was a change in the mpv API, version 1.0.6 of python-mpv will fix this issue.

**Comment by polyzen** [comment]
Pushed python-mpv 1.0.6 to extra-testing as I'm currently unable to test it: \
https://archlinux.org/packages/extra-testing/any/python-mpv/

**Comment by mauricioquintela** [comment]
Indeed python-mpv 1.0.6 fixes the issue. Thank you for the help. Closing
