### ISSUE TITLE
Crashes On Certain Keys

### ISSUE THREAD

**Issue by Jumblemuddle** [iwalton3/plex-mpv-shim#12]
When a key like `u` or `w` is accidentally hit, the player crashes without any meaningful logs.
Should this functionality work? Perhaps we could just disable keys that are known to not work?

**Comment by iwalton3** [comment]
The u and w keys are custom shortcuts. `u` marks the video as unwatched and quits. `w` marks the video as watched and quits.

Currently there is no way to disable or rebind the shortcuts. There is a list of the other shortcuts in the README.

**Comment by Jumblemuddle** [comment]
Ah... that's my bad; I just assumed they did the normal MPV things. :) I'll read the documentation.
