### ISSUE TITLE
Shim not detecting a finished movie?

### ISSUE THREAD

**Issue by nzupancic** [iwalton3/plex-mpv-shim#13]
I'm casting from the Plex web app using the local connection script. After the movie ends mpv player closes and in the browser you get thrown back to the last screen but the Shim client doesn't seem to detect that movie ended and keeps "updating timeline to all subscribers". Looking at the console output this is what keeps printing even after everything is done: 

>2020-04-02 22:01:18,961 [   DEBUG] subscribers: RemoteSubscriberManager::addSubscriber refreshed y1e0py1i6njjuashzy1ya9wj
2020-04-02 22:01:18,962 [   DEBUG] subscribers: RemoteSubscriber::refresh y1e0py1i6njjuashzy1ya9wj (cid=11)
2020-04-02 22:01:19,916 [   DEBUG] timeline: TimelineManager::SendTimelineToSubscribers updating all subscribers 

Now this also causes an issue inside the browser because every time it refreshes this, the web app reloads (the loading circle in the middle of the screen appears). On top of that you can't use the "continue where you stopped" function because the pop up window where you can select whether you'd like to continue or start over is closed immediately because of this. Without restarting the Shim client I wasn't able to stop the refreshing loop.

This doesn't happen if you watch a TV show or playlist since it autoplays the next video and it can also be avoided by just closing mpv a second or 2 before the video ends so it's not a huge issue but I was wondering if this was encountered before and if it could be solved with a correct configuration?  I tried adding the line keep-open=always to mpv.conf file but it didn't seem to have any effect on the behaviour after ending.

I'm using Plex web app in Firefox, using the Local connection script with Grease monkey, mpv (0.32.0) on Linux Mint 19.3

**Comment by iwalton3** [comment]
This is a known bug that was actually a mild annoyance for me. I didn't know it broke the web client that much.

I'll investigate it and post here when I've got a release to fix it.

**Comment by iwalton3** [comment]
This is now fixed in version 1.7.15.
