### ISSUE TITLE
Seeking is no longer available in the Android app

### ISSUE THREAD

**Issue by colemickens** [iwalton3/plex-mpv-shim#14]
I used to be able to seek through episodes, but I can't anymore.

**Comment by iwalton3** [comment]
It still works for me. Anything interesting in the logs if you set `mpv_log_level` to `debug`? (File is `~/.config/plex-mpv-shim/conf.json`)

I tried seeking with the arrow keys, clicking the OSD, and from the web app. All of them worked.

**Comment by iwalton3** [comment]
Also try restarting `plex-mpv-shim` and see if the problem goes away. Maybe it crashed somehow and needs to be restarted?

**Comment by colemickens** [comment]
1. restarting doesn't help, I'm running it manually and restarting plenty
2. no, mpv itself is working fine. If I use the keyboard on the computer I can seek just fine.

When I start playing media in the Plex app in Android, I no longer get a remote (the remote and OSD does work). It used to be that it showed a seekable progress bar with the usual controls (and +/- 10 seconds buttons). Now it only shows "fwd/back track" and an unseekable bar.

**Comment by colemickens** [comment]
Maybe we're using it differently. When you say "from the webapp", what webapp do you mean? When I load plex via `plex.tv` I am not usually able to see local players.

**Comment by iwalton3** [comment]
Strange. I wonder if an update to the Android app broke it. Can you confirm that it still works from the web app?

> When I load plex via plex.tv I am not usually able to see local players.
You can see any players that are on the same network as the Plex server. You can circumvent that restriction with [this userscript](https://greasyfork.org/en/scripts/398049-mpv-shim-local-connection), but it only applies to the application running on the same computer unless you change the IP address in the script.

**Comment by colemickens** [comment]
Oh it's even in the README. This is great! It seems to all work great from the UI with that very simple workaround. I actually much prefer this over using the Android app.

I will say that it wouldn't surprise me if they changed something, but for whatever it's worth, the Android app works "as expected" with the same server + Chromecast.

**Comment by iwalton3** [comment]
Ok. Yeah then this is associated with the android app. It still works on iOS and the web app.

Unfortunately I don't have any android devices so this may be difficult for me to look at.

**Comment by Xalaxis** [comment]
Timeline seeking is working for me from the app.

Android app version: 8.0.0.17051 (c1815a9f)
Server version: 1.19.1.2645
Shim version: 1.7.15

**Comment by iwalton3** [comment]
@colemickens Are you still affected by this on Android with the latest Plex Android app?

**Comment by iwalton3** [comment]
Closing due to stale issue and report of it working from another user. Please open the issue again if it is still a problem.
