### ISSUE TITLE
Modifying input.config doesn't seem to matter.

### ISSUE THREAD

**Issue by epistularum** [iwalton3/plex-mpv-shim#17]
I've downloaded the standard mpv input.cong and edited a line to have a 2s seek instead of 5s.
I can confirm it works with a regular mpv install but modifying plex-mpv-shim's mpv.conf with the exact same parameters doesn't affect at all plex-mpv-shim's behaviour.

**Comment by iwalton3** [comment]
That's because I override the seek buttons to also allow menu navigation. I'm in the process of reworking the override shortcuts to be configurable. I'll add configuration options for the seek time too.

**Comment by epistularum** [comment]
Glad to see you're already on top of the issue!

**Comment by iwalton3** [comment]
This change has been applied to master and will be in the next release.

**Comment by epistularum** [comment]
Should I open the same issue for jellyfin-mpv-shim?

**Comment by iwalton3** [comment]
No need, it already has a pending fix: https://github.com/iwalton3/jellyfin-mpv-shim/commit/f897b67d85f17602698e36d66c51ebb98a481423

**Comment by iwalton3** [comment]
The fix for this is in the latest version.
