### ISSUE TITLE
iptables

### ISSUE THREAD

**Issue by fruitloop** [iwalton3/plex-mpv-shim#20]
hi,

I just managed to inatall your project on my machine and stream from the web client as well as the android client (in the same wifi).
however I have not yet figured out what exactly needs to be opened in iptables to actually allow the android client to stream.

can anyone help me there?

thanks

**Comment by iwalton3** [comment]
Please see: https://github.com/iwalton3/plex-mpv-shim#development

**Comment by fruitloop** [comment]
perfect, thanks
