### ISSUE TITLE
Buffer more than 2 minutes at a time

### ISSUE THREAD

**Issue by nonamethanks** [iwalton3/plex-mpv-shim#21]
I'm not sure if this is limited by plex itself, but adding either of these lines to the mpv.conf file at `%appdata%\plex-mpv-shim\` does nothing:
```
demuxer-readahead-secs=3600
cache=1000000
```
(I know cache is deprecated but since the demuxer one did not work I tried that too)
The player only prefetches about 2 minutes (betweeen 1:30 and 2:30, probably because it's fetched in chunks) and then stops in all cases until there's less than 2 minutes prefetched. Am I doing something wrong or is it not possible to preload more?

**Comment by iwalton3** [comment]
Is it transcoding? Plex might be throttling the stream. I don't set any cache settings, so it would be whatever the MPV defaults are.

**Comment by nonamethanks** [comment]
Nope, it's direct play. 
Even setting mpv to be launched externally and setting the config there doesn't load more than 2 minutes at a time. It just stops once it gets to the 2 minutes threshold.

**Comment by iwalton3** [comment]
Silly question. Are you restarting the client between changes to the config file?

**Comment by nonamethanks** [comment]
Yes, both client and the plex mpv shim process.

**Comment by iwalton3** [comment]
What happens with this config?
```
cache=yes
demuxer-max-bytes=123400KiB
demuxer-readahead-secs=20
```

**Comment by nonamethanks** [comment]
Nope, it has no effect, at least for the external one.

**Comment by iwalton3** [comment]
If you disable log file sanitization in the config, you might be able to try downloading the video file in a web browser that is sent to MPV. I’d be curious if the download was slow or stalled.

**Comment by nonamethanks** [comment]
How can I see the logs? Launching plex-mpv-shim.exe in cmd does not show any output. The log level is set to info.

**Comment by iwalton3** [comment]
Use the "Show Console" option in the systray icon.

**Comment by nonamethanks** [comment]
Alright, from the logs I can see that the program keeps polling, but from the GUI I see the cache just stops increasing after the 2 minutes mark. Even a look at the network tab for task manager confirms this. Meanwhile downloading the plex url with CURL successfully goes beyond the 3 minutes mark.

The program keeps polling even after it stops downloading, but for some reason it just doesn't download anything. I see every 30 seconds or so there's a new entry in the logs
```
2020-08-13 04:42:56,749 [   DEBUG] HttpHandler::handle_request request to '/player/timeline/poll?[...]'
2020-08-13 04:42:56,749 [   DEBUG] RemoteSubscriberManager::addSubscriber refreshed 6gfr26h2lh2atxhbdxzk65ia
2020-08-13 04:42:56,749 [   DEBUG] RemoteSubscriber::refresh 6gfr26h2lh2atxhbdxzk65ia (cid=1)
```

but my network tab looks like this
![image](https://user-images.githubusercontent.com/12946050/90088468-4fc11500-dd1f-11ea-82cb-38965440ca1b.png)

**Comment by iwalton3** [comment]
Fun. From my standpoint I just give the Plex URL directly to MPV, so this is probably an MPV issue.

**Comment by nonamethanks** [comment]
Ah yea, bummer, it looks like it is, playing the plex url on MPV externally returns the same results. I guess this can be closed then.

**Comment by iwalton3** [comment]
Closing, as this is an upstream issue. Let me know if there is any updates on this.
