### ISSUE TITLE
The server "plex" does not have a valid connection for casting

### ISSUE THREAD

**Issue by ddonindia** [iwalton3/plex-mpv-shim#23]
MPV running on: Linux/Windows 64Bit

Plex: Version 1.20.1.3252 , Docker
Plex host: Raspberry OS 64Bit,  4GB RAM.

I am getting following error while trying to play on remote MPV:
```
The server "plex" does not have a valid connection for casting. Check that the server is claimed in server settings.
```
Both server and MPV running on same LAN,  do I need to login on plex server to use this app?

**Comment by iwalton3** [comment]
The application requires https by default, which I think requires a signed-in Plex server. You could try setting `allow_http` to false in the config, but I can't assure that will work.

It is very possible that casting just requires a signed-in Plex server. It wouldn't surprise me at all.

**Comment by ddonindia** [comment]
no luck with `allow_http`.  Guess its time to move to Jellyfin :).
Thanks for your help
