### ISSUE TITLE
Using MPV scripts doesn't work and also using MPV externally

### ISSUE THREAD

**Issue by Nahte101** [iwalton3/plex-mpv-shim#33]
I tried using scripts and put them in the correct directories (%appdata%plex-mpv-shim/scripts) but nothing came of it. I even tried doing external mpv execution by changing the config file to open to a mpv executable that works with scripts and even if i open that mpv beforehand it'll still open it's own instance. What am i doing wrong?

**Comment by iwalton3** [comment]
The scripts folder isn't mapped. For scripts to work you need to specify the full path to each script in the mpv.conf.

**Comment by RafeeDaBoy** [comment]
@iwalton3 How would the syntax for mapping a script in mpv.conf would be like?
