### ISSUE TITLE
It might be stupid but External MPV from SVP never worked... Help

### ISSUE THREAD

**Issue by co-sine** [iwalton3/plex-mpv-shim#34]
Everytime when I casted, the bulit-in mpv player pops out.
Let alone getting SVP to work.. 
System: Windows 10

Here is my setting of conf

    "adaptive_transcode": false,
    "allow_http": false,
    "always_transcode": false,
    "audio_ac3passthrough": false,
    "audio_dtspassthrough": false,
    "auto_play": true,
    "auto_transcode": false,
    "client_profile": "Plex Home Theater",
    "client_uuid": "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx",
    "direct_limit": false,
    "enable_gui": true,
    "enable_osc": false,
    "enable_play_queue": true,
    "fullscreen": true,
    "http_port": "3000",
    "idle_cmd": null,
    "idle_cmd_delay": 60,
    "idle_when_paused": false,
    "kb_debug": "~",
    "kb_menu": "c",
    "kb_menu_down": "down",
    "kb_menu_esc": "esc",
    "kb_menu_left": "left",
    "kb_menu_ok": "enter",
    "kb_menu_right": "right",
    "kb_menu_up": "up",
    "kb_next": null,
    "kb_pause": null,
    "kb_prev": null,
    "kb_stop": null,
    "kb_unwatched": null,                    * it never disabled the shortcut as well
    "kb_watched": null,                        * it never disabled the shortcut as well
    "log_decisions": false,
    "media_ended_cmd": null,
    "media_key_seek": false,
    "mpv_ext": true,
    "mpv_ext_ipc": mpvpipe,               * tried typed in 'null', still not working
    "mpv_ext_path": "C:\\Personal Program\\SVP\\mpv64\\mpv.exe",
    "mpv_ext_start": true,
    "mpv_log_level": "info",
    "player_name": "PC",
    "pre_media_cmd": null,
    "sanitize_output": true,
    "seek_down": null,
    "seek_left": null,
    "seek_right": null,
    "seek_up": null,
    "shader_pack_custom": false,
    "shader_pack_enable": false,          * tried to use my own shaders in %appdata%/mpv/shaders
    "shader_pack_profile": null,
    "shader_pack_remember": true,
    "skip_intro_always": false,
    "skip_intro_prompt": false,
    "stop_cmd": null,
    "stop_idle": false,
    "subtitle_color": "#FFFFFFFF",
    "subtitle_position": "bottom",
    "subtitle_size": 100,
    "svp_enable": true,
    "svp_socket": mpvpipe,
    "svp_url": "http://127.0.0.1:9901/",    * already set SVP to use remote API, with 9901 port
    "transcode_kbps": 20000

I am really into this tool, and I am really really appreciate your contribution.
But, please help me to get it to work. External mpv (installed from SVP manager), and SVP

**Comment by iwalton3** [comment]
```
"mpv_ext_ipc": mpvpipe,               * tried typed in 'null', still not working
```
needs quotes around the `mpvpipe` like `"mpvpipe"`.
You may also need to use a downloaded copy of MPV following the directions here, as I am not sure if the SVP MPV is new enough: https://github.com/iwalton3/plex-mpv-shim#svp-integration-1

**Comment by co-sine** [comment]
It worked!! THANK YOU!!
SVP version of MPV is new enough I guess.
