### ISSUE TITLE
Ssl certificate has expired

### ISSUE THREAD

**Issue by Skandery** [iwalton3/plex-mpv-shim#52]
This week (just before the plex update) received the error "An error occurred trying to play this item."

And I found this in the logs :

```Exception occurred during processing of request from ('192.168.1.68', 1335)
Traceback (most recent call last):
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\SK\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
```

To fix it I just did a `pip install --upgrade certifi` and now it works  (jellyfin-mpv-shim have `ignore_ssl_cert` for this kind of problem maybe).

I don't know if it's the right place  but I think it could help people who have the same problem.

**Comment by co-sine** [comment]
I definitely have the exactly same issue as yours!! So Thankful for sharing this!!
However I am not a Python user (code idiot), to do the command I guess I need to install tha Python and cd to Plex to Shim and pip install it?

**Comment by LAP87** [comment]
I did the upgrade, but didn't solve my error when trying to play via mpv shim since last week

**Comment by PurpleRobin** [comment]
I also did the upgrade and still not working the plex console shows "incomplete TLS handshake from [IP Address]:: sslv3 alert certificate expired. I asked for the cert to be reset in the plex forums but was told it wasn't expired.

**Comment by iwalton3** [comment]
https://github.com/iwalton3/plex-mpv-shim/suites/3977456141/artifacts/100049578

**Comment by co-sine** [comment]
> https://github.com/iwalton3/plex-mpv-shim/suites/3977456141/artifacts/100049578

hate to say this but the "An error occurred trying to play this item." error remains after reinstalling.

**Comment by LAP87** [comment]
> 
> 
> https://github.com/iwalton3/plex-mpv-shim/suites/3977456141/artifacts/100049578

This one solved my issue, thanks a bunch.

**Comment by iwalton3** [comment]
Here is the thread for Jellyfin MPV Shim, where users are having a similar issue. (Although Jellyfin users tend to use Let's Encrypt which had a recent CA Root expire and not Plex's CA which I am not sure what they use.)

I posted some information there too. https://github.com/jellyfin/jellyfin-mpv-shim/issues/235

**Comment by co-sine** [comment]
I agree to add the ignore_ssl_cert option.. manully importing certifi is quite a complex job for me..

**Comment by iwalton3** [comment]
Yeah I realized there were like a dozen different places and two different requests libraries being used. Maybe the explicit certifi dependency might be easier.

**Comment by co-sine** [comment]
> Yeah I realized there were like a dozen different places and two different requests libraries being used. Maybe the explicit certifi dependency might be easier.

I've been trying alternative solutions none, none of them is that perfect like MPV shim, if you make it happens, I'll be really, really, really appreciate it.

**Comment by co-sine** [comment]
Pretty sure it is something system wise (CA?) goes wrong, I tried a fresh install of Shim in Windows Sandbox it worked again...

**Comment by jsravn** [comment]
Made a PR to use certifi in various places. It fixes the issue for me on Windows.

**Comment by iwalton3** [comment]
https://github.com/iwalton3/plex-mpv-shim/releases/tag/v1.10.3
