### ISSUE TITLE
This has likely been asked before but I cannot get MPV to work externally

### ISSUE THREAD

**Issue by Tensai-Otaku** [iwalton3/plex-mpv-shim#59]
These are my current config settings

{
    "adaptive_transcode": false,
    "allow_http": false,
    "always_transcode": false,
    "audio_ac3passthrough": false,
    "audio_dtspassthrough": false,
    "auto_play": true,
    "auto_transcode": true,
    "client_profile": "Plex Home Theater",
    "client_uuid": "SECRET",
    "direct_limit": false,
    "enable_gui": true,
    "enable_osc": true,
    "enable_play_queue": true,
    "fullscreen": true,
    "http_port": "3000",
    "idle_cmd": null,
    "idle_cmd_delay": 60,
    "idle_when_paused": false,
    "kb_debug": "~",
    "kb_menu": "c",
    "kb_menu_down": "down",
    "kb_menu_esc": "esc",
    "kb_menu_left": "left",
    "kb_menu_ok": "enter",
    "kb_menu_right": "right",
    "kb_menu_up": "up",
    "kb_next": ">",
    "kb_pause": "space",
    "kb_prev": "<",
    "kb_stop": "q",
    "kb_unwatched": "u",
    "kb_watched": "w",
    "log_decisions": false,
    "media_ended_cmd": null,
    "media_key_seek": false,
    "mpv_ext": true,
    "mpv_ext_ipc": null,
    "mpv_ext_path":"C:\\Program Files (x86)\\SVP 4\\mpv64\\mpv.exe",
    "mpv_ext_start": true,
    "mpv_log_level": "info",
    "player_name": "DESKTOP",
    "pre_media_cmd": null,
    "sanitize_output": true,
    "seek_down": -60,
    "seek_left": -5,
    "seek_right": 5,
    "seek_up": 60,
    "shader_pack_custom": false,
    "shader_pack_enable": true,
    "shader_pack_profile": null,
    "shader_pack_remember": true,
    "skip_intro_always": false,
    "skip_intro_prompt": true,
    "stop_cmd": null,
    "stop_idle": false,
    "subtitle_color": "#FFFFFFFF",
    "subtitle_position": "bottom",
    "subtitle_size": 100,
    "svp_enable": true,
    "svp_socket": "mpvpipe",
    "svp_url": "http://127.0.0.1:9901/",
    "transcode_kbps": 2000
}

**Comment by iwalton3** [comment]
`"mpv_ext_path":"C:\Program Files (x86)\SVP 4\mpv64\mpv.exe", ` should be `"mpv_ext_path":"C:\\Program Files (x86)\\SVP 4\\mpv64\\mpv.exe", `

**Comment by Tensai-Otaku** [comment]
> 

Wow, thank you for the swift reply. Sadly, it still didn't work

**Comment by Tensai-Otaku** [comment]
I was able to at least get SVP to work, but the external functionality is not working. I fixed the path as you stated. Now I just start MPV normally and play a video, right? That's what I am doing with no good results

**Comment by iwalton3** [comment]
No you should be able to start the application and cast something to it

**Comment by Tensai-Otaku** [comment]
> No you should be able to start the application and cast something to it

I can cast directly from the Plex app, but that's not what I want. I want to be able to open MVP locally and have Plex track it using my own custom MPV settings and setup. Perhaps that's not possible and I have mistaken the feature for something else? I've already tried opening MPV and then opening up a file that is uploaded to the Plex server but to no avail.

**Comment by iwalton3** [comment]
The feature causes the MPV Shim application to use whatever MPV version you want. It still launches MPV and controls it from the Plex application through casting.

I added an option to tell MPV to use your configuration in the Jellyfin counterpart but I don’t think it was backported to the Plex version.

You can set it to control an MPV instance you already have open but you still must cast to it.

**Comment by iwalton3** [comment]
Oh also you can change settings in the MPV config that is used by MPV Shim as well.

**Comment by Tensai-Otaku** [comment]
> Oh also you can change settings in the MPV config that is used by MPV Shim as well.

If I am understanding right when the configuration is correct. Upon opening Shim it will open an instance of MPV based on my own custom setup, is that right? So if I have been able to accomplish that, it's safe to say it works? However, casting from MPV through Plex makes it possible for it to keep track of my history using TauTulli (https://tautulli.com/). How do I accomplish that here, or is that simply not possible yet?

**Comment by iwalton3** [comment]
> I added an option to tell MPV to use your configuration in the Jellyfin counterpart but I don’t think it was backported to the Plex version.

I did finally port it back, use the dev build here if you want that: https://nightly.link/iwalton3/plex-mpv-shim/actions/artifacts/159514531.zip

**Comment by RafeeDaBoy** [comment]
Hey, could you explain what is external mpv is? Does it mean playing videos from Plex in an already standard install of mpv with all of it's config and scripts?
