### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by colemickens** [iwalton3/plex-mpv-shim#6]
I'm happy to send a PR if you can give me highlights.

How does Plex find this player? Also, in that question, what ports need to be open on hte machine running `plex-mpv-shim` in order for it to be visible to a plex instance running elsewhere, or other plex clients on other devices on the network?

Thanks!

**Comment by colemickens** [comment]
Yeah, I've tried opening a variety of ports, and it only seems to work when I wholesale turn off my firewall, which I'd like to avoid on my laptop that roams networks, etc.

```
networking.firewall.allowedTCPPorts = [ 32400 32467 ];
networking.firewall.allowedUDPPorts = [ 5353 32467 32400 32410 32412 32413 32414 44777 ];
```

**Comment by iwalton3** [comment]
From what I can tell, it needs to listen on ports UDP 32412 and TCP 3000. Please let me know if this works. If not, I’ll look at it more tomorrow.

**Comment by colemickens** [comment]
I guess I hadn't managed to get the right combination despite having tried both of those at one point.

I'll send a PR with what I found.

**Comment by colemickens** [comment]
see: https://github.com/iwalton3/plex-mpv-shim/pull/7

**Comment by colemickens** [comment]
Thanks a bunch for the fast help and merge! I'd had this in the back of my head for a while, had no idea this existed already. Can't wait to get another RPi and hack up a more open Chromecast replacement. Cheers!
