### ISSUE TITLE
Skip ahead to next or previous episode?

### ISSUE THREAD

**Issue by kanjieater** [iwalton3/plex-mpv-shim#67]
I couldn't find a way to skip ahead or backwards in the playlist from MPV. Is this only possible in plex?

**Comment by iwalton3** [comment]
There are keyboard shortcuts documented in the README to do this. It should also be possible from the controlling application.

**Comment by kanjieater** [comment]
Ah thank you, I did miss that. It seems that you cannot go back before the episode that you started on, but you can go forward to the next episode as far as plex would. Is there some way to go back multiple episodes?

**Comment by iwalton3** [comment]
Plex sends a play queue that doesn’t contain any previous episodes, so unfortunately there is no way currently to do it.

Well except it *might* be possible if you disable play queue support but I haven’t tested this. `enable_play_queue` is the setting for that.
