### ISSUE TITLE
Appreciation Post

### ISSUE THREAD

**Issue by LampPrinter** [iwalton3/plex-mpv-shim#80]
Just a appreciation post. I am part of of 2-3 very good Plex servers which can saturate my 200 Mbps download speed, if I download anything from them.

But the Plex web client was always very slow for me. So much so I'd rather download the files first.
Skipping around the timeline would take anywhere between 5-15 seconds. 

plex-mpv-shim completely changed that. It opens faster and skipping around is so much better. I am watching stuff in 4k now. 😜

**Comment by BradleyShaner** [comment]
That's probably because the web interface was having to transcode your streams. If you use the desktop Plex app it would most likely direct play.

I'm not saying plex-mpv-shim isn't great, because of course it is, but I just wanted you to know that there are other reasons for your issue 😄

**Comment by LampPrinter** [comment]
> Plex's desktop app uses MPV internally, essentially the same thing as plex-mpv-shim minus the shaders. You don't need to try it but it's a fact that it performs better than the web player which historically has far fewer codecs that it can direct play.
Actually, I preferred the desktop app than web. But there is not a native Apple Silicon version and it was kind of laggy.
