### ISSUE TITLE
Plex-MPV-Shim detected by Plex but cannot be selected

### ISSUE THREAD

**Issue by shag00** [iwalton3/plex-mpv-shim#90]
Not sure if this is the same as Issue 87. Anyway in Plex when I go to set plex-mpv-shim it is an available selection as expected but when I click on it nothing happens and the little radio box next to the spanner does not turn yellow and mpv is not the player used.
![plex1](https://user-images.githubusercontent.com/37562304/237027028-fab8a2ed-9a47-49d3-8443-f7d1c9418a3f.png)

I have just upgraded Kubuntu to 23.04 and Plex to Server Version 1.32.1.6999.

When looking at some Plex logs there is reference to a 404 error.

EDIT 1:
Seems it may be a Plex bug as reverting to an earlier build partially fixed the issue. I can now select mpv shim but cannot start a movie, if I select a start point anywhere else in the movie it will play from that point.

**Comment by hyperactive68** [comment]
Same thing happened to me. Shim also doesn't even show up anymore on my android phone.

**Comment by escalade** [comment]
Updated for the first time in a few months and got this issue as well. Reverted back to the previous version I was using and all is good.

Link to working version: https://downloads.plex.tv/plex-media-server-new/1.29.2.6364-6d72b0cf6/redhat/plexmediaserver-1.29.2.6364-6d72b0cf6.x86_64.rpm

**Comment by hyperactive68** [comment]
I'm using a windows PC and got it working by going into the network settings and putting it on private instead of public.

**Comment by shag00** [comment]
> I'm using a windows PC and got it working by going into the network settings and putting it on private instead of public.

I went to settings>settings>network and could not find a private/public switch. Where exactly is this control located?

**Comment by hyperactive68** [comment]
> > I'm using a windows PC and got it working by going into the network settings and putting it on private instead of public.
> 
> I went to settings>settings>network and could not find a private/public switch. Where exactly is this control located?

Looked up a quick video. [Here you go.](https://www.youtube.com/watch?v=wtloKS_2-d4)

**Comment by shag00** [comment]
Thanks for that. It is a system setting rather than a Plex setting and not sure what the Ubuntu equivalent is.

**Comment by arlinsandbulte** [comment]
I am having this issue too.  I think [90](https://github.com/iwalton3/plex-mpv-shim/issues/87) is the same issue (I'm cross-posting to there).
And, I think this is an issue with the Plex Server.  I cannot cast from the web client to Roku or "Plex MPV Shim".
Here is an issue on Plex support confirming, I think.  https://forums.plex.tv/t/plex-web-flinging-casting-broken/837738

My Plex Server Version 1.32.5.7516 
My Plex Web Client Version: Version 4.115.2

**Comment by shag00** [comment]
It appears a beta has been released for Plex pass holders, Plex Media Server 1.32.8.7639 but not yet available for general download.

**Comment by arlinsandbulte** [comment]
@shag00 
Does that beta resolve this issue?

**Comment by arlinsandbulte** [comment]
I can confirm.  Plex Server 1.32.8.7639 has fixed this issue for me!
FINALLY!

**Comment by escalade** [comment]
Confirmed fixed here as well thanks :)

**Comment by shag00** [comment]
@arlinsandbulte 
I am not a Plex Pass holder so I have not been able to download the new server but I am pleased that a couple of you are and have installed the new server.

**Comment by shag00** [comment]
Plex server version 1.32.8.7639 solves the problem of selecting a player.

**Comment by arlinsandbulte** [comment]
I don't think this is an issue with Plex MPV Shim, but ever since this casting issue was fixed, I cannot use the video transport controls on the casting PC.  And the progress bar does not work.
Anyone else notice this?
