### ISSUE TITLE
The server "" does not have a valid connection for casting. Check that the server is claimed in server settings

### ISSUE THREAD

**Issue by Jerrk** [iwalton3/plex-mpv-shim#98]
I'm unable to use the shim even with the userscript mentioned in #87, tried both firefox and chrome

It will connect to the shim but when i try to play any media it will buffer for a while and then throw the error `The server "" does not have a valid connection for casting. Check that the server is claimed in server settings`

I've checked the logs on both the shim and the server itself but it doesnt seem to show any entries at all when trying to cast.

The server is claimed, i am logged in, tried setting "allow_http" to both true and false.

The only thing that works is casting via android but i just cannot get it to work on desktop.

I thought it might have something to do with the authentication since the same message was fixed by logging in in #23 .

Weird thing is casting **did work** on the "plex for windows" desktop app just 2 days ago but then suddenly stopped working yesterday. and i cannot for the life of me think of anything that i have changed.

**Comment by iwalton3** [comment]
This is because the Greasemonkey script fakes out Plex with a fake, invisible cast server it injects into the API. I will have to take a look at it.

**Comment by iwalton3** [comment]
I pulled down the latest Plex version from linuxserver.io and tested with the Greasemonkey script. It still works for me. I can't reproduce the issue.

**Comment by Jerrk** [comment]
Hmm you're right if i go via app.plex.tv the script works but not if i access it via its local ip.

Does this mean that you cannot cast to the shim without internet access?

**Comment by Jerrk** [comment]
not an issue casting from the local plex webui any longer, works without the previously mentioned error.

Plex server Version 1.32.8.7639
